Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -24,15 +24,14 @@ jobs:
 
       - name: Validate and Extract Version
         run: |
-          version="${{ env.RELEASE_VERSION }}"
-
-          if [[ "$version" =~ (^|[^a-zA-Z0-9])V?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?($|[^a-zA-Z0-9]) ]]; then
-            echo "RELEASE_VERSION=$(echo "$version" | grep -oE 'V?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?')" >> $GITHUB_ENV
-          else
-            echo "Error: Input does not contain a valid version format (X.X.X or VX.X.X)."
-            exit 1
-          fi
-
+            clean_version=$(echo "${{ env.RELEASE_VERSION }" | grep -oE 'V?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?')
+        
+            if [ -n "$clean_version" ]; then
+              echo "RELEASE_VERSION=$clean_version" >> $GITHUB_ENV
+            else
+              echo "Error: Input does not contain a valid version format (X.X.X, VX.X.X, or VX.X.X-suffix)."
+              exit 1
+            fi
 
       - uses: actions/checkout@v3
         with:
